/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// hahaha
public class Library {
	public static void main(String arg[]) {
		System.out.println("Kim changed the codes and fail the lab2");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}

